### ISSUE TITLE
Update TS support

### ISSUE THREAD

**Issue by chriskrycho** [chriskrycho/ember-simple-track-helper#104]
- [ ] Add 4.9 to the matrix (we’re testing against it by dint of being on it already)
- [ ] Update the README to include it

**Comment by chriskrycho** [comment]
Related, here, @SergeAstapov – next time, *before* we cut a major, let’s make a point to revisit the versions of TS  we support. In this case, there was no *particular* reason to drop support for older versions of TS, but it’s always worth evaluating when we are going to make a breaking change whether we should bundle in changes to TS and/or Node at that point. (In this case, there are no features we would even *want* to use that matter, I think, given how tiny this library is!)

**Comment by SergeAstapov** [comment]
@chriskrycho point taken, thanks for explanation. don't remember exact reason why the change was made but agree it worth to be more carefull

**Comment by SergeAstapov** [comment]
@chriskrycho FYI here is the CI run that complained about TS 4.2 and 4.1 https://github.com/chriskrycho/ember-simple-track-helper/actions/runs/3453701778/jobs/5764513611

seem like https://www.npmjs.com/package/@tsconfig/ember uses `"target": "ES2021"` which is has TS 4.3+ support if I'm reading logs from above run correctly?

**Comment by chriskrycho** [comment]
Yep, and targeting 4.3 was totally good and fine here—not a problem at all, to be clear! I was actually meaning that we might want to go *even later* than that: it'd be perfectly acceptable to target 4.5 or 4.6 if there was reason to!
