### ISSUE TITLE
Support Ember 4.x

### ISSUE THREAD

**Issue by chriskrycho** [chriskrycho/ember-simple-track-helper#73]
Upgrade to ember-auto-import v2 and add webpack v5.

**Comment by SergeAstapov** [comment]
@chriskrycho would you like to add me as contribution? I'd like to handle those items as well as convert this to v2 embroider native add-on if that makes sense

**Comment by chriskrycho** [comment]
That sounds excellent. Will do!

**Comment by SergeAstapov** [comment]
this was completed in #96

**Comment by SergeAstapov** [comment]
@chriskrycho FYI v2.0.0 was published 🎉

**Comment by chriskrycho** [comment]
Awesome!
